name: build
on:
  push:
    branches-ignore:
      - 'master' 
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: docker://cdssnc/docker-lint
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build the Docker image
      run: docker build . -t docker.pkg.github.com/pyaillet/ctf-tools/ctf-tools:latest
    needs: [lint]
